export const ADD_CAT = 'ADD_CAT';
export const REMOVE_CAT = 'REMOVE_CAT';
export const CHANGE_CAT_NAME = 'CHANGE_CAT_NAME';
export const CHANGE_CAT_IMAGE = 'CHANGE_CAT_IMAGE';

export const ADD_IMAGE = 'ADD_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const RESET_IMAGES = 'RESET_IMAGES';
export const SHUFFLE_IMAGES = 'SHUFFLE_IMAGES';

export const SET_USERS = 'SET_USERS';
export const UPSERT_USER = 'UPSERT_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const START_USER_REQUEST='START_USER_REQUEST';
export const USER_REQUEST_ERROR='USER_REQUEST_ERROR';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';
export const CLEAR_USER_SUCCESS = 'CLEAR_USER_SUCCESS';

export const SET_TODOS = 'SET_TODOS';
export const UPSERT_TODO = 'UPSERT_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';

export const START_TODOS_REQUEST='START_TODOS_REQUEST';
export const TODOS_REQUEST_ERROR='TODOS_REQUEST_ERROR';
export const TODOS_REQUEST_SUCCESS = 'TODOS_REQUEST_SUCCESS';
export const CLEAR_TODOS_ERROR = 'CLEAR_TODOS_ERROR';
export const CLEAR_TODOS_SUCCESS = 'CLEAR_TODOS_SUCCESS';

