export const ADD_CAT = 'ADD_CAT';
export const REMOVE_CAT = 'REMOVE_CAT';
export const CHANGE_CAT_NAME = 'CHANGE_CAT_NAME';
export const CHANGE_CAT_IMAGE = 'CHANGE_CAT_IMAGE';

export const ADD_IMAGE = 'ADD_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const RESET_IMAGES = 'RESET_IMAGES';
export const SHUFFLE_IMAGES = 'SHUFFLE_IMAGES';

export const START_USER_REQUEST='START_USER_REQUEST';
export const USER_REQUEST_ERROR='USER_REQUEST_ERROR';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';
export const CLEAR_PROFILES = 'CLEAR_PROFILES';
export const SET_USERS = 'SET_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const SELECT_USER = 'SELECT_USER';
export const UNSELECT_USER = 'UNSELECT_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const CLEAR_USER_SUCCESS = 'CLEAR_USER_SUCCESS';

export const FETCH_TODOS='FETCH_TODOS';
export const TODOS_REQUEST_ERROR='TODOS_REQUEST_ERROR';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const POST_TODO = 'POST_TODO';
export const DELETE_TODO = 'DELETE_TODO';
