export const ADD_EMPLOYEE = 'ADD_EMPLOYEE',
  REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE ',
  MODIFY_EMPLOYEE = 'MODIFY_EMPLOYEE';

export const ADD_PRODUCT = 'ADD_PRODUCT',
  REMOVE_PRODUCT = 'REMOVE_PRODUCT ',
  MODIFY_PRODUCT = 'MODIFY_PRODUCT';

